// Automatically generated by astro-icon
// 290e869937b9b1f1a961760b2f2c41dc9d7e163d0fafb1e884ea93f2c96c3731

declare module 'virtual:astro-icon' {
	export type Icon = 
		| "mdi:facebook"
		| "mdi:instagram"
		| "mdi:whatsapp"
		| "mdi:telegram"
		| "mdi:github";
}