// Automatically generated by astro-icon
// 65c5255e9510234ff49169bec50f4bb277daf77eba67d83b1f28f3f715728eb2

declare module 'virtual:astro-icon' {
	export type Icon = 
		| "mdi:facebook"
		| "mdi:instagram"
		| "mdi:whatsapp"
		| "mdi:telegram"
		| "mdi:github"
		| "mdi:heart";
}