// Automatically generated by astro-icon
// 6ee203a65ab7b0d7b8ca1106029addd073f87a78b008e5952505d684a03b5546

declare module 'virtual:astro-icon' {
	export type Icon = 
		| "mdi:facebook"
		| "mdi:instagram"
		| "mdi:whatsapp"
		| "mdi:telegram"
		| "mdi:github"
		| "mdi:heart";
}